name:                solarmonitor
version:             0.1.0.0
github:              "rtrollebo/solarmonitor"
license:             BSD3
author:              "Robert Trollebø"
maintainer:          "rtrollebo@@gmail.com"
copyright:           "2021 Robert Trollebø"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rtrollebo/solarmonitor#readme>

dependencies:
- base >= 4.7 && < 5
- wreq
- aeson
- text
- lens
- aeson-lens
- containers
- http-conduit 
- bytestring 
- time
- text-conversions

library:
  source-dirs: src

executables:
  solarmonitor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solarmonitor

tests:
  solarmonitor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solarmonitor
